version: '3.8'

services:
  scrabble-score-app:
    build: .
    container_name: scrabble-score-app
    ports:
      - "8080:80"
    volumes:
      - ./data/scrabble.db:/var/www/html/includes/database.db
    restart: unless-stopped
